---
title: "DiD"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(magrittr)
library(ggplot2)
load(url("https://github.com/tpemartin/Econometric-Analysis/blob/master/data/public.rda?raw=true"))
```

```{r}
public %>%#只是轉換變數
  mutate_at(
    vars(EMPFT,EMPPT,EMPFT2,EMPPT2),
    funs(as.numeric)
    ) -> public  
```

```{r}
public %>% 
  group_by(STATE) %>% # 1 if NJ; 0 if Pa
  summarise(mFT_before=mean(EMPFT,na.rm=T),
            mPT_before=mean(EMPPT,na.rm=T),
            mFT_after=mean(EMPFT2,na.rm=T),
            mPT_after=mean(EMPPT2,na.rm=T)) %>%
  ungroup ->
  employment_change
```
```{r}
library(kableExtra)
employment_change %>% 
  select(STATE,mFT_before,mFT_after) %>%
  kable("html")
```
#回歸模型
```{r}
public%>%
  select(STATE,EMPFT,EMPFT2)
```

```{r}
library(tidyr)
public %>% 
  select(STATE,EMPFT,EMPFT2) %>%
  group_by(STATE) %>%
  gather(type,emp,-STATE) -> public2
```

```{r}
public2 %>%
  mutate(
    STATE1=(STATE==1),
    AFTER=(type=="EMPFT2"),
    PolicyImpact=STATE1*AFTER
  ) -> public2
public2
```
```{r}
public2%>%
  mutate(
    STATE1=(STATE==1),
    AFTER=(type=="EMPFT2"),
    PolicyImpact=STATE*AFTER
  )->public2
```
```{r}
lm(emp~STATE1+AFTER+PolicyImpact,data=public2)->DD_result
DD_result
```
```{r}
lm(emp~STATE1+AFTER+I(STATE1*AFTER),data=public2)
```
#factor()的應用
```{r}
lm(emp~STATE1+AFTER,data=public2)
```


```{r}
lm(emp~factor(STATE)*factor(type),data=public2)
```
```{r}

```

