---
title: "R for TSLS"
author: "姓名"
date: "3/6/2019"
output: 
  html_document: 
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: true
      smooth_scroll: false
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=T)
```

```{r}
library(dplyr)
library(magrittr)
library(AER)
data("CigarettesSW")
```

```{r}
class(CigarettesSW)
```
#是dataframe任何和dtat有關的操作都能用在裡面


as_tibble() #改變class的特性
```{r}
CigarettesSW %>% as_tibble() -> CigarettesSW # 串接
as_tibble(CigarettesSW) -> CigarettesSW # 非串接
```

```{r}
class(CigarettesSW)
```

```{r}
CigarettesSW
```

library(magrittr)#要有這個套件才有%<>%
```{r}
CigarettesSW %<>% as_tibble()
CigarettesSW %>% as_tibble() -> CigarettesSW 
#上下等價是一樣的
```

```{r}
CigarettesSW %>% 
  filter(year=="1995") -> 
  CigarettesSW
```

```{r}
CigarettesSW %<>% filter(year=="1995")
```

```{r}
CigarettesSW %>% 
  mutate(
    rprice=price/cpi,
    rincome=income/(population*cpi),
    tdiff=(taxs-tax)/cpi
  ) -> CigarettesSW
```

```{r}
model1 <- log(packs) ~ log(rprice) 
model2 <- log(packs) ~ log(rprice) + log(rincome)
```

```{r}
model1noConstant <- 
  log(packs) ~ log(rprince)+0#不要常數向
model1noConstant2 <- 
  log(packs) ~ log(rprince)-1
```

```{r}
class(model1)
```

# OLS 
```{r}
ols1<-lm(model1,CigarettesSW)
ols2<-lm(model2,CigarettesSW)
```


```{r}
library(sandwich)
library(lmtest)
library(stargazer)

#使用vcovHC函數來計算HC1型的異質變異（即橫斷面資料下的線性迴歸模型）
lmtest::coeftest(ols1, vcov. = sandwich::vcovHC, type="HC1") -> ols1_coeftest
coeftest(ols2, vcov. = vcovHC, type="HC1") -> ols2_coeftest
```

```{r}
ols1_coeftest
ols2_coeftest
```

```{r}
ols1#沒HC
ols1_coeftest#有HC
```


```{r}
library(stargazer)
stargazer(ols1,ols2,type="html")
```

```{r, results="asis"}
stargazer(ols1_coeftest, ols2_coeftest, 
          se=list(ols1_coeftest[,"Std. Error"], ols2_coeftest[,2]),
          type="text",
          align=TRUE)
```

TSLS
```{r}
tsls_1iv <- ivreg(
  log(packs) ~ log(rprice) + log(rincome) | log(rincome) + tdiff,
  data=CigarettesSW
  ) 

tsls_2iv <- ivreg(
  log(packs) ~ log(rprice) + log(rincome) | log(rincome) + tdiff + I(tax/cpi),
  data=CigarettesSW
  )
```


```{r}
library(broom)
broom::glance(tsls_1iv)
broom::augment(tsls_1iv)
broom::tidy(tsls_1iv)
```

```{r}
class(tsls_1iv)
```


```{r}
summary(tsls_1iv)
```


```{r}
summary(tsls_1iv, vcov = sandwich, diagnostics = TRUE, df=Inf) -> tsls_1iv_tests
summary(tsls_2iv, vcov = sandwich, diagnostics = TRUE, df=Inf) -> tsls_2iv_tests
```


Sargan: exclusiveness test
```{r}
summary(tsls_1iv, vcov = sandwich, diagnostics = TRUE, df=Inf)
```

```{r}
summary(tsls_2iv, vcov = sandwich, diagnostics = TRUE, df=Inf)
```
```{r, results="asis"}
stargazer(tsls_1iv,tsls_2iv,type="html",
          column.labels = c("one IV", "two IVs"),
          add.lines = list(c("TSLS tests p-value", "",""),
                           c("Q1: Sargan","NA","0.5641"),
                           c("Q2: Weak instruments","1.4e-08","<2e-16"),
                           c("Q3: Wu-Hausman","0.263","0.0569")
                           ))
```

